### ISSUE TITLE
Error: invalid order function for sorting

### ISSUE THREAD

**Issue by melkster** [ten3roberts/qf.nvim#4] opened 2022-09-09 18:29 UTC
After populating the quickfix list, qf.nvim throws the following error on `CursorHold`:

```language
Error detected while processing CursorHold Autocommands for "*":
Error executing lua callback: .../pack/packer/start/qf.nvim/lua/qf/util.lua:93: invalid order function for sorting
stack traceback:
        [C]: in function 'sort'
        .../pack/packer/start/qf.nvim/lua/qf/util.lua:93: in function 'sorted_list_items'
        .../pack/packer/start/qf.nvim/lua/qf.lua:373: in function 'strategy_func'
        .../pack/packer/start/qf.nvim/lua/qf.lua:494: in function 'follow'
        .../pack/packer/start/qf.nvim/lua/qf.lua:859: in function <...er/nvim-test-config/pack/packer/start/qf.nvim/lua/qf.lua:858>
```

**To reproduce:**

Use the following `init.lua`:

<details>
<summary><b>Click to expand</b></summary>

```lua
-- Ignore default config and plugins
vim.opt.runtimepath:remove(vim.fn.expand('~/.config/nvim'))
vim.opt.packpath:remove(vim.fn.expand('~/.local/share/nvim/site'))

-- Append test directory
local test_dir = vim.fn.expand('~/code-other/nvim-test-config')
vim.opt.runtimepath:append(vim.fn.expand(test_dir))
vim.opt.packpath:append(vim.fn.expand(test_dir))

-- Install packer
local install_path = test_dir .. '/pack/packer/start/packer.nvim'
local install_plugins = false

if vim.fn.empty(vim.fn.glob(install_path)) > 0 then
  vim.cmd('!git clone https://github.com/wbthomason/packer.nvim ' .. install_path)
  vim.cmd('packadd packer.nvim')
  install_plugins = true
end

local packer = require('packer')

packer.init({
  package_root = test_dir .. '/pack',
  compile_path = test_dir .. '/plugin/packer_compiled.lua'
})

packer.startup(function()
  function Use(module)
    use(require(string.format('configs.%s', module)))
  end

  -- Packer can manage itself
  packer.use 'wbthomason/packer.nvim'


  use { 'ten3roberts/qf.nvim', -- Quickfix utilities
    config = function()
      local qf = require('qf')

      qf.setup({
        pretty = false,
        l = {
          wide = true,
          min_height = 3,
        },
        c = {
          wide = true,
          min_height = 3,
        },
      })
    end
  }


  if install_plugins then
    packer.sync()
  else
    -- load plugins at your earliest convenience
    vim.defer_fn(function()
      vim.cmd('doautocmd User LoadPlugins')
    end, 1)
  end
end)
```

</details>

1. `> nvim -u path/to/config/above/init.lua`
2. Populate quickfix, for instance by running `:helpgrep lua`
3. Wait a couple of seconds for `CursorHold` to trigger
4. Error message shows up

Neovim nightly version: NVIM v0.8.0-dev-1059-g2d6735d8c

**Comment by ten3roberts** [comment] 2022-09-11 13:20
This should now be fixed by 63deb0ecd16f57543e551c5e3d0725e938ad6fe7

It was caused by bufnr comparison always yielding true in a comparison function

**Closed by ten3roberts** 2022-09-11 13:20 UTC
